# Generated by Django 4.1.5 on 2023-01-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lunch_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Person",),
        migrations.DeleteModel(name="Species",),
    ]
